### ISSUE TITLE
Alternative communication protocol between server and agent?

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes-sigs/apiserver-network-proxy#146]
Currently, communication tunnel between agent and server is based on gRPC. Before using ANP, I used to set up the tunnel using TCP.  I did a small benchmark to compare the performance of using gRPC (i.e., ANP) over TCP. As expect, using gRPC introduces some extra overheads. 

Run `kubectl exec test-po -- date` 100 times thorugh gRPC tunnel
```bash
 pkts      bytes target  prot opt in     out     source               destination
2730   530312            tcp   --   *       *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8091
2758   491823            tcp   --   *       *       0.0.0.0/0            0.0.0.0/0            tcp spt:8091
```  

Run `kubectl exec test-po -- date` 100 times through TCP tunnel
```bash
  pkts      bytes target  prot opt in     out     source               destination
 3608   397313            tcp   --   *       *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8091
 3729   420205            tcp   --   *       *       0.0.0.0/0            0.0.0.0/0            tcp spt:8091
```

There're cases where tunnel may need to go through the public network, and lowering the overhead can help the user to save some costs.  Should we consider having an alternate to gRPC?

**Comment by charleszheng44** [comment]
Or, maybe we can add gRPC compressor to reduce the bandwidth?

**Comment by cheftako** [comment]
+1
There is already a mode flag to control the communication between client (KAS) and server. We always new we would also want one between agent and server. I had been imagining it would be more likely to enable something like VPN support but your welcome to look at adding an optimized for bandwidth alternative.

**Comment by charleszheng44** [comment]
@cheftako Thanks for reply.

**Comment by mvladev** [comment]
Fundamentally, for multiplexing ,  TCP is a bad choice due to [head of line](https://en.wikipedia.org/wiki/Head-of-line_blocking) problems which can affect all streams in the single TCP connection.

I've played around with [quic](https://github.com/lucas-clemente/quic-go) and the native support for streams in the protocol make the implementation of the server and agent quite trivial. See this repo - https://github.com/mvladev/quic-reverse-http-tunnel:

```
apiserver --- TCP ----> [proxy-server] ---- QUIC ----> [proxy-agent]---TCP--> [kubelet]
```

1. the proxy-server listens for `tcp` (no HTTP server running) and `quic`.
1. The proxy-agent talks to the server and opens a `quic` session.
1. It starts a HTTP tunnel server that listens on that session for new streams.
1. When the API server / curl talks to the proxy-server, it creates a new `quic` stream and sends the data to the proxy-agent.
1. The HTTP server in the proxy-agent that listens on new `quic` streams accepts the stream, opens `tcp` connection to the requested host (from the CONNECT) and pipes the data back.
