### ISSUE TITLE
Is multi cluster multi master scenario supported?

### ISSUE THREAD

**Issue by yanyhui** [kubernetes-sigs/apiserver-network-proxy#186]
For multiple clusters, such as three clusters, the clusters are master and node, master, master and node respectively; whether the network proxy supports this scenario, how the network proxy is implemented, and how the network between clusters communicates?

**Comment by cheftako** [comment]
Hi, I'm a little confused by your question. We do support a multi-master cluster. The standard configuration for that would be 3 masters (each running a local proxy server) and some number of nodes (at least some of which are running agents). This normally works via the agents connecting to the proxy server via a load balancer. The proxy server is configured with a count of the number of masters (https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cmd/server/main.go#L153). It returns this to any connecting agents. The agent will then retry connection requests until it has connected to that number of servers. That covers multi master. Not sure what you mean by a multi cluster Kubernetes. As far as I know there is not standard interconnection between Kubernetes clusters. Happy to chat about how this might be used in your use case but I would need to better understand what you are trying to achieve.

As far as communication goes; there are two sets of tunnels, one set between KASs (Kubernetes API-Server) and Proxy servers. another set between proxy servers and agents. The KAS<->Proxy Server communication is defined by our konnectivity-client library, compiled into the KAS. It supports either HTTPS-Connect or GRPC over HTTPS; I would suggest using the GRPC over HTTPS mode. Since this is compiled into the KAS, these are currently your only options. We have only built a GRPC over HTTPS tunnel for the Proxy-Server<->Proxy-Agent communication. However as both ends are a reference implementation, this communication can be swapped out with something else you build and meets your needs.

**Comment by yanyhui** [comment]
thanks

**Comment by yanyhui** [comment]
> 嗨，您的问题让我有些困惑。我们确实支持多主机集群。该服务器的标准配置是3个主服务器（每个主服务器运行一个本地代理服务器）和一些节点（至少其中一些正在运行代理）。通常，这是通过代理通过负载平衡器连接到代理服务器来实现的。代理服务器配置有主机数量的计数（https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cmd/server/main.go#L153）。它将其返回给任何连接代理。然后，代理将重试连接请求，直到它已连接到该数量的服务器为止。那涵盖了多主。不确定多集群Kubernetes是什么意思。据我所知，Kubernetes集群之间没有标准的互连。很高兴谈论在您的用例中如何使用它，但是我需要更好地了解您要实现的目标。
> 
> 就交流而言；有两组隧道，一组在KAS（Kubernetes API服务器）和代理服务器之间。代理服务器和代理之间的另一组。KAS <-> Proxy Server通信由我们的konnectivity-client库定义，并编译到KAS中。它支持HTTPS-Connect或HTTPS上的GRPC。我建议在HTTPS模式下使用GRPC。由于已将其编译到KAS中，因此，当前这些是您唯一的选择。我们仅为Proxy-Server <-> Proxy-Agent通信构建了基于HTTPS隧道的GRPC。但是，由于两端都是参考实现，因此可以将这种通信与您构建的其他满足您需求的东西交换掉。

**Comment by yanyhui** [comment]
@cheftako 
The cluster has three master nodes and one root node, and the network between the master node and the root node is not connected. In this case, the master node communicates with the root node through ANP. The first question is: do the three master nodes establish a set of ANP proxy communication with the root node? The second question is: among the three established ANP communication lines, does the customer's request randomly select one line to distribute to the root node? Is the load balancing component added here? What is the specific processing mechanism here?

**Comment by Jefftree** [comment]
Each root/cluster node runs an agent that establishes a tunnel to every master node. The master nodes can then use these tunnels to proxy traffic to the cluster nodes. Please see the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1281-network-proxy#proposal) for more details.

For question 2, the default mechanism is to select a random node to route the request to. @charleszheng44 added support for targeted routing based on the IP address so that might be something worth looking into as well.
