### ISSUE TITLE
Refine code of main.go: only reserve main() function in main.go file

### ISSUE THREAD

**Issue by liufen90** [kubernetes-sigs/apiserver-network-proxy#226]
Refine code of main.go: only reserve main() function in main.go file. Create app directory under cmd/agent and cmd/server. Transfer structs and functions to app directory. For example, https://github.com/kubernetes/kubernetes/tree/master/cmd/kube-controller-manager

**Comment by liufen90** [comment]
@cheftako, when will we release a newer version? I need to use the refine code of main.go in next version. Thank you very much.

**Comment by cheftako** [comment]
@liufen90 I assume your looking for the #227 change. I thought this was a code forklift rather than bug fix or feature addition. Curious to understand what you mean release a new version. That change has merged into the mainline. We have not cut a new release with it (v0.0.20 will be the next release) but not I understand if thats what you are asking for? If it is I would like to better understand how that is useful?

**Comment by liufen90** [comment]
@cheftako  Yes, I look for #227 change. I need to import functions and structs from app package instead of copying them in my project. Issue: https://github.com/kubeedge/kubeedge/issues/2869

**Comment by cheftako** [comment]
Very cool!
/cc @Jefftree can you take care of cutting a v0.0.20 release?

**Comment by liufen90** [comment]
> Very cool!
> /cc @Jefftree can you take care of cutting a v0.0.20 release?

Thank you very much.

**Comment by Jefftree** [comment]
v0.0.20 has been released

**Comment by liufen90** [comment]
> v0.0.20 has been released

Thank you very much!

**Comment by Jefftree** [comment]
I think this is fixed?

/close
