### ISSUE TITLE
Issues with CreateSingleUseGrpcTunnel

### ISSUE THREAD

**Issue by ash2k** [kubernetes-sigs/apiserver-network-proxy#357]
1. `CreateSingleUseGrpcTunnel()` does not allow to use different contexts for dialing and connection lifetime control. There seem to be no way to shut the tunnel down.
2. Context cancellation/timeout in `grpcTunnel.DialContext()` doesn't interrupt any I/O, doesn't signal to the `serve()` goroutine in any way. This is suspicious and is possibly a source of connection leaks.

See this thread and PR for background https://github.com/kubernetes/kubernetes/pull/110079#discussion_r874800421.

**Comment by jkh52** [comment]
This is marked rotten/stale, but I would argue that at this point it is fixed.

> CreateSingleUseGrpcTunnel() does not allow to use different contexts for dialing and connection lifetime control. There seem to be no way to shut the tunnel down.

This concern is still valid, but because of kube-apiserver connection re-use, there isn't an obvious way to close the single-use tunnel until the client calls `Close` on the `net.Conn` (actually a konnectivity `client.conn`).

> Context cancellation/timeout in grpcTunnel.DialContext() doesn't interrupt any I/O, doesn't signal to the serve() goroutine in any way. This is suspicious and is possibly a source of connection leaks.

This was fixed by https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/360.
