### ISSUE TITLE
Handle requests from the Cluster to the Control Plane

### ISSUE THREAD

**Issue by texascloud** [kubernetes-sigs/apiserver-network-proxy#36]
[In the proposal for this repo](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190226-network-proxy.md), this sentence is present under "Non-Goals":

> (The proxy can be extended to do this. However that is left to the User if they want that behavior)

Any suggestions as to how to extend this to get this behavior?

Thank you

**Comment by cheftako** [comment]
I believe there are a few things which need to be solved to get this behavior.

Are you planning on using this for all traffic from the Kubelet to the KAS?
If so the agent cannot run as a DaemonSet and the Kubelet will not be a fully functioning Node until after the agent is up and connected. This suggests that the agent will need to be configured as a static pod or even as a systemd service.

The next issue is the server and agent are not currently symmetric. You can make a connection request to the server which will be forwarded to the agent. Right now only the server accepts dial requests https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/agent/agentserver/server.go#L119. You will need to add an ability to do a dial request to the agent client. The server will then need to be able to handle that and then put the relevant packets on its local network. You will need to stream handling in the reverse direction. You will also probably want to add authentication to the agent for incoming requests to it. (See https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/cmd/proxy/main.go#L212)

Fairly sure this is all doable, but the scope was large enough I didn't want to add it to our initial roll out. Feel free to join the apiserver-network-proxy slack channel if you have further questions.

**Comment by cheftako** [comment]
> [This](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/agent/agentclient/client.go#L114) looks like the client accepts dial requests

Technically true, but that is specifically for handling the dial request which was forwarded to it from the server. To do what you want you need a dial request which goes in the other direction. Instead of 

client (KAS) --> proxy server --> proxy agent --> endpoint (?Kubelet/Pod) 

you want something like 

endpoint (KAS) <-- proxy server <-- proxy agent <-- client (?Kubelet/Pod)

It would probably make sense for the proxy-agent to add another port/handler to accept dial requests from clients. It could definitely make sense for the agent to accept tokens/certs. Although that means you might have to do an auth request of the KAS prior to forwarding the traffic.

**Comment by CamelCaseNotation** [comment]
> Although that means you might have to do an auth request of the KAS prior to forwarding the traffic.

What do you mean prior to forwarding the traffic?

Assuming the tunnel is open, a client request to the agent would have to be forwarded no matter what so the KAS can do auth. This would mean there is no need to put auth logic in this repo for this flow:

> endpoint (KAS) <-- proxy server <-- proxy agent <-- client (?Kubelet/Pod)

Does that make sense?

**Comment by cheftako** [comment]
> > Although that means you might have to do an auth request of the KAS prior to forwarding the traffic.
> 
> What do you mean prior to forwarding the traffic?
> 
> Assuming the tunnel is open, a client request to the agent would have to be forwarded no matter what so the KAS can do auth. This would mean there is no need to put auth logic in this repo for this flow:

At some level your choice. For KAS traffic to the cluster we have authentication. Given that the konnectivity server is running on the master node, it in some sense has escalated privileges. So you should consider how you want to secure the traffic which goes through the tunnel. One aspect is you may want to apply a filter such as only letting traffic destined for the KAS through. If your sure that only traffic from the cluster can hit the agent, that may be sufficient. You may however want to consider allowing traffic to be authenticated. 

> > endpoint (KAS) <-- proxy server <-- proxy agent <-- client (?Kubelet/Pod)
> 
> Does that make sense?

I may have been thinking too much of trying to make the directions symmetric. With a filter to prevent the tunnel being used for anything other than KAS, that may be sufficient. Its worth noting that if your sensitive to traffic volume that it may be cheaper to authenticate the request before you send it rather than sending large requests to the KAS and then having them declined.

**Comment by timoreimann** [comment]
With @irozzo-1A's KEP merged, this feature request may now be implemented. I created #171 to track the overall progress, please subscribe to that one for further updates.
