### ISSUE TITLE
Expose gRPC `MaxConnectionIdle` configuration

### ISSUE THREAD

**Issue by tallclair** [kubernetes-sigs/apiserver-network-proxy#383]
The gRPC [server KeepAlive params](https://pkg.go.dev/google.golang.org/grpc/keepalive#ServerParameters) include
```go
type ServerParameters struct {
	// MaxConnectionIdle is a duration for the amount of time after which an
	// idle connection would be closed by sending a GoAway. Idleness duration is
	// defined since the most recent time the number of outstanding RPCs became
	// zero or the connection establishment.
	MaxConnectionIdle time.Duration // The current default value is infinity.
	// ...
}
```

This could be a useful knob to expose through configuration for mitigating connection leaks.

**Comment by rata** [comment]
@tallclair I'm not sure if that would really help and it _might_ hurt for long lived connections or need to close connections going through that one? I can't remember, but it might not be as easy (maybe it is, though!)

For example, that didn't help for any of the two leaks in  #276. It didn't help for some other leaks either IIRC, and maybe due to the way tunneling is done maybe it is not very likely this will help? Unsure.

We can definitely think about this more and see if it makes sense or just try it.

**Comment by tallclair** [comment]
I think that with the current way we use gRPC this wouldn't do anything for us. My understanding that this would affect connections to the gRPC server when there aren't any open streams. However, we don't reuse gRPC connections (on the client or agent), so this doesn't get us anything.
