### ISSUE TITLE
How to deal with multi proxy-server?

### ISSUE THREAD

**Issue by yingxin-gh** [kubernetes-sigs/apiserver-network-proxy#570]
If we want build multi proxy-server(e.g, three proxy-server),  I find that the GrpcProxyAgentOptions struct only have one pair of parameters as below. It can only config one host/port. I want to config three pair of proxy-server, they are have different ip, how can I config it ?
```
type GrpcProxyAgentOptions struct {
// Configuration for connecting to the proxy-server
ProxyServerHost string
ProxyServerPort int
...
```

**Comment by jkh52** [comment]
Currently, the reference implementation of Konnectivity Proxy assumes that multiple proxy-server are made available to agents through a load balancer. (And that the load balancer distributes in a round-robin fashion; so that agents can eventually bootstrap connections to all servers).

The only other option (a mode where each agent is directly configured with a list of server addresses) is still work in progress: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/493

Feel free to reopen if you have more questions.
