### ISSUE TITLE
Use sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.0.5?

### ISSUE THREAD

**Issue by liggitt** [kubernetes-sigs/apiserver-network-proxy#62]
Now that the client is tagged, should the root go.mod switch to using that version?

**Comment by Jefftree** [comment]
We are planning to keep the version numbers in sync between the root and client code. Since a commit in the root repository tagged v0.0.x contains the code for a v0.0.x client, pointing to the local directory should achieve the same effect as specifying the corresponding version. This also gives us more flexibility as the master branches of the two modules will be able to reference each other without needing to cut a new release.

/cc @caesarxuchao

**Comment by liggitt** [comment]
> pointing to the local directory should achieve the same effect as specifying the corresponding version

it also doesn't work for anyone using `go get` to fetch this module

**Comment by liggitt** [comment]
Using v0.0.0 and a replace directive effectively makes the root module unsuitable for anyone to depend on. If the intent is to only support the client module as a library, and only support the top-level module as a built binary (e.g. to not support `go get` or use as a library), that's worth calling out

**Comment by Jefftree** [comment]
> If the intent is to only support the client module as a library, and only support the top-level module as a built binary (e.g. to not support go get or use as a library), that's worth calling out

ack, I believe this was the intent with creating a separate client library for others to import.
