### ISSUE TITLE
Issue with tag konnectivity-client/v0.0.5

### ISSUE THREAD

**Issue by Sh4d1** [kubernetes-sigs/apiserver-network-proxy#72]
There seems to be an issue with the tag `konnectivity-client/v0.0.5`. In fact the `_GIT_TAG` given to the prow job building the image is `v20200218-konnectivity-client/v0.0.5-3-gef0d890` which fails the docker build since it's not a valid tag. 

If we want to name a tag with the component name as well I guess it should be done in a docker tag way like `konnectivity-client-v0.0.5`.

/cc @Jefftree

**Comment by Jefftree** [comment]
Unfortunately we can't change the `konnectivity-client/v0.0.5` tag structure due to it being a requirement to be recognized as a separate go mod. At the same time, docker does not support slashes in their tags.

We can annotate the `v0.0.5` tag and keep `konnectivity-client/v0.0.5` as a lightweight tag. `git describe --tags` (in the cloudbuild) will then ignore the lightweight tag and use `v0.0.5` as the tag. I think this should fix the cloudbuild issue.

/cc @caesarxuchao

**Comment by Jefftree** [comment]
We'll cut a new release once https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/58 is merged.

**Comment by Jefftree** [comment]
This is fixed with v0.0.6.

/close
