### ISSUE TITLE
serveRecvBackend should check if dialResp contains error

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes-sigs/apiserver-network-proxy#79]
In case of dial failure, agent sets the error: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/da0186e6db180d4ff153be228cc7465bfe44425f/pkg/agent/agentclient/client.go#L140

But the proxy server never checks for error: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/da0186e6db180d4ff153be228cc7465bfe44425f/pkg/agent/agentserver/server.go#L425

I haven't thought through what outcome would be.

**Comment by Jefftree** [comment]
I don't think this is related to any of the k/k test failures so this can be lower priority.

The outcome is that the connection is assumed to be established and client will try to send data. When the error occurs, the agent sends the DIAL_RSP packet back and since we don't check to error on the proxy server side, the tunnel is assumed to be established

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/da0186e6db180d4ff153be228cc7465bfe44425f/pkg/agent/agentclient/client.go#L139-L145

The client will hang since it'll try to send data but the data will just disappear and no response will be given. The data sent by the client will be dropped by the agent since we don't have a data channel for the particular connection (we need an else statement to log this). 

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/da0186e6db180d4ff153be228cc7465bfe44425f/pkg/agent/agentclient/client.go#L187-L189

A simple way to simulate this is for `conn, err := net.Dial(dialReq.Protocol, dialReq.Address)` to fail by dialing to a port with no listener, eg:

```
./bin/proxy-server --uds-name=konnectivity-server.socket --mode=http-connect --cluster-cert=certs/agent/issued/proxy-master.crt --cluster-key=certs/agent/private/proxy-master.key --server-port=0
./bin/proxy-agent --ca-cert=certs/agent/issued/ca.crt --agent-cert=certs/agent/issued/proxy-agent.crt --agent-key=certs/agent/private/proxy-agent.key
./bin/proxy-test-client --proxy-uds=konnectivity-server.socket --proxy-host= --proxy-port=0 --mode=http-connect --request-port=8888 --request-host=localhost --request-path=/
```

I can work on a fix for this

**Comment by Jefftree** [comment]
@caesarxuchao I created https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/94 to prevent us from adding an unnecessary frontend if the dial fails.

In GRPC mode, we send the packet back to the client and the client checks whether the error field is nil before sending data.

In HTTP Connect mode, unfortunately we don't have an easy way of signaling dial error because we never send a DIAL RSP to the client.

https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/server/server.go#L58

We can probably send a 500 header, but I'm also not sure how we can pass an error message through an HTTP connection.

**Comment by Jefftree** [comment]
Just realized, per https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/94 we close the connection in HTTP Connect mode so this should be handled for both modes.


/close
